# Pipeline para módulo de Regulaciones
# Ejecuta las pruebas del módulo de regulaciones (autorizaciones, módulos, visitas)

trigger:
  branches:
    include:
      - LineaBase
      - main
      - master
  paths:
    include:
      - SISDEP-LineaBase/tests/features/regulaciones/*
      - SISDEP-LineaBase/page_objects/autorizaciones_page.py
      - SISDEP-LineaBase/page_objects/modulos_page.py
      - SISDEP-LineaBase/page_objects/visitas_page.py
      - SISDEP-LineaBase/pipelines/03-regulaciones.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  moduleName: 'regulaciones'
  reportPath: '$(System.DefaultWorkingDirectory)/SISDEP-LineaBase/reports/$(moduleName)'

stages:
- stage: TestRegulaciones
  displayName: 'Ejecutar Pruebas - Regulaciones'
  jobs:
  - job: RunTests
    displayName: 'Ejecutar Tests de Regulaciones'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Configurar Python $(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r SISDEP-LineaBase/requirements.txt
      displayName: 'Instalar dependencias'

    - script: |
        playwright install chromium
        playwright install-deps chromium
      displayName: 'Instalar Playwright y navegadores'

    - script: |
        cd SISDEP-LineaBase
        mkdir -p reports/$(moduleName)
        pytest tests/features/regulaciones/ \
          -v \
          -m "regulaciones" \
          --html=reports/$(moduleName)/report.html \
          --self-contained-html \
          --junitxml=reports/$(moduleName)/junit.xml
      displayName: 'Ejecutar pruebas de Regulaciones'
      continueOnError: true

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/junit.xml'
        testRunTitle: 'Pruebas de Regulaciones'
        failTaskOnFailedTests: false
      displayName: 'Publicar resultados de pruebas'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/SISDEP-LineaBase/reports/$(moduleName)'
        artifactName: 'Reporte-Regulaciones'
        publishLocation: 'Container'
      displayName: 'Publicar reporte HTML'

